### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by Watersdr** [mkloubert/nativescript-apiclient#2]
I just want to make sure I understand the need for this plugin and I wasn't really sure where else to pose this question. What is the difference between using this plugin vs. the `fetch` module that is built into the tns-core-modules?  Thanks!

**Comment by mkloubert** [comment]
Some examples:

You ...

* ... have much more control (e.g. [handling response](https://github.com/mkloubert/nativescript-apiclient#responses))
* ... can define [routes](https://github.com/mkloubert/nativescript-apiclient#routes)
* ... can use [authorizers](https://github.com/mkloubert/nativescript-apiclient#authorization)
* ... can use [shortcut request methods](https://github.com/mkloubert/nativescript-apiclient#authorization)

**Comment by Watersdr** [comment]
Ahhh very cool. This seems extremely simple and easy to work with. Guess I should have read the Readme more thoroughly :P Thanks for the quick response!
